### ISSUE TITLE
CRUD - Fazenda

### ISSUE THREAD

**Issue by carlafcf** [carlafcf/AgroFamiliar#7]
**TO DO**

2. Criar URLS
3. Criar Views
4. Criar Templates
5. Testar

Detalhes: criar um função do zero
Editar: usar UpdateView
Deletar: usar DeleteView

**Comment by jcarloscody** [comment]
TO DO

Criar Aplicação
Criar MODEL
Criar URLS (criar, lista)
Criar Views (criar, lista)
Criar Templates (criar, lista)
Testar
Criar: usar CreateView
Listar: criar uma função do zero
Detalhes: criar um função do zero

**Comment by jcarloscody** [comment]
DONE

Criar Aplicação
Criar MODEL
Criar URLS (criar, lista)
Criar Views (criar, lista)
Criar Templates (criar, lista)
Testar
Criar: usar CreateView
Listar: criar uma função do zero
Detalhes: criar um função do zero
